[project]
name = "crewai-experiment"
version = "0.1.0"
description = "A simple CrewAI experiment"
authors = ["Your Name <your.email@example.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
start = "python src/main.py"
ui = "streamlit run src/ui/app.py"
test = "pytest tests/"
coverage-report = "pytest --cov=src --cov-report=html:coverage tests/"

[dependencies]
python = ">=3.10,<3.13"  # Ensuring compatibility with PyO3
pip = "*"

[pypi-dependencies]
crewai = ">=0.100.0"  # Using latest version for decorator-based approach
crewai-tools = ">=0.0.10"  # Adding tools package
python-dotenv = ">=1.0.1"
pyyaml = ">=6.0.1"
streamlit = ">=1.31.1"
streamlit-chat = ">=0.1.1"
pytest = ">=8.0.0"
pytest-asyncio = ">=0.23.5"
pytest-mock = ">=3.12.0"
pytest-cov = ">=4.1.0"
google-search-results = ">=2.4.2"  # SerpAPI client
langchain = ">=0.1.4"
langchain-community = ">=0.0.16"
langchain-core = ">=0.1.17"
beautifulsoup4 = ">=4.12.3"
requests = ">=2.31.0"
pydantic = ">=2.6.1"
black = ">=24.1.1"
isort = ">=5.13.2"
mypy = ">=1.8.0"
pylint = ">=3.0.3"
