task_templates:
  default_topic: "AI and Machine Learning"
  research_task:
    description: >
      Research the following topic: {topic}
      
      Requirements:
      1. Use the Web Search Tool to gather information by passing the topic directly.
      2. IMPORTANT: Use the exact citations provided by the web search tool in your response.
      3. Verify facts across different sources when possible.
      4. Include ALL citations from the web search in your response.
      5. Evaluate source credibility and relevance.
      6. Provide a comprehensive analysis with recent developments.

      Format your response with:
      - Key findings with inline citations exactly as provided by the web search tool
      - Critical analysis of the information
      - Identification of any conflicting information
      - Assessment of source reliability
      - Include the complete bibliography section from the web search
    expected_output: >
      A comprehensive analysis of {topic} with:
      1. Key findings and insights with proper citations
      2. Source credibility assessment
      3. Complete bibliography with all sources
    agent: researcher
    context:
      - "Use web search tool to gather recent information"
      - "Verify facts across multiple sources"
      - "Include all citations from web search"
      - "Evaluate source credibility"
      - "Provide comprehensive analysis"

  writing_task:
    description: >
      Write a clear and engaging summary of the research findings about {topic}.
      
      Requirements:
      1. Use ALL citations from the research exactly as provided
      2. Format in markdown with proper headings and bullet points
      3. Include the complete bibliography section
      4. Ensure every fact has its corresponding citation
      5. Group related information from multiple sources
      6. Maintain the exact citation format from the research
    expected_output: >
      A well-formatted markdown summary of the research findings about {topic},
      including proper citations and a complete bibliography.
    agent: writer
    context:
      - "Use research findings as primary source"
      - "Format in markdown with proper structure"
      - "Include all citations from research"
      - "Group related information logically"
      - "Maintain citation format consistency"

  editing_task:
    description: >
      Review and evaluate the content for {topic}.
      
      Requirements:
      1. Review the research and writing for accuracy and completeness
      2. Verify that all citations are properly used
      3. Check that the content fully addresses the topic
      4. Evaluate the clarity and organization
      5. Verify that all claims are supported by sources
      6. Check for any gaps in information
      
      Your response MUST:
      1. Start with either "APPROVED: " or "NEEDS REVISION: "
      2. If approved, provide a brief explanation of why
      3. If needs revision, list specific issues that need to be addressed
      4. Be concise and clear in your feedback
      
      Example approved format:
      APPROVED: Content is accurate, well-organized, and properly cited. All requirements are met.
      
      Example revision format:
      NEEDS REVISION:
      - Citation missing for claim about X
      - Section Y needs more detail
      - Bibliography incomplete
    expected_output: >
      A clear decision (APPROVED or NEEDS REVISION) with specific feedback about {topic}.
      Must start with either "APPROVED: " or "NEEDS REVISION: " followed by detailed explanation.
    agent: editor
    context:
      - "Review research and writing content"
      - "Verify citation accuracy and completeness"
      - "Check topic coverage and organization"
      - "Evaluate clarity and coherence"
      - "Assess source support for claims"
      - "Provide clear approval or revision requirements"
