research_task:
  description: >
    Research the following topic: {topic}
    Provide a comprehensive analysis including recent developments, key points, and relevant context.
  expected_output: >
    A comprehensive analysis of {topic} with key findings and insights.
  agent: researcher

writing_task:
  description: >
    Write a clear and engaging summary of the research findings about {topic}.
    Format it in markdown with proper headings and bullet points where appropriate.
  expected_output: >
    A well-formatted markdown summary of the research findings about {topic}.
  agent: writer
  context:
    - research_task
