name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install pixi
      run: |
        curl -fsSL https://pixi.sh/install.sh | bash
        echo "$HOME/.pixi/bin" >> $GITHUB_PATH
    
    - name: Cache pixi environment
      uses: actions/cache@v3
      with:
        path: ~/.pixi
        key: ${{ runner.os }}-pixi-${{ hashFiles('**/pixi.toml') }}
        restore-keys: |
          ${{ runner.os }}-pixi-
    
    - name: Install dependencies
      run: |
        pixi install
    
    - name: Run tests with coverage
      run: |
        pixi run test
    
    - name: Generate coverage report
      run: |
        pixi run coverage-report
      if: always()
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/
      if: always() 